/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.biopark.queijos.atualizador;

import br.biopark.queijos.atualizador.enumerator.EPropertie;
import br.biopark.queijos.atualizador.util.Downloader;
import br.biopark.queijos.atualizador.util.FlywayDatabase;
import br.biopark.queijos.atualizador.util.PropFile;
import br.biopark.queijos.atualizador.util.UnzipFiles;
import br.biopark.queijos.atualizador.util.Util;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author Renato
 */
public class Progress extends javax.swing.JFrame {

    private static Util util = new Util();
    private static PropFile prop = new PropFile();
    private static FlywayDatabase flywayDb = new FlywayDatabase();
    private static Downloader downloader = new Downloader();
    private static String versaoAtual = "";
    private static List<String> versoes = new ArrayList();
    private static Progress INSTANCE;

    private Progress() {
        initComponents();
        URL url = this.getClass().getResource("/queijo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    public static Progress getInstance() {
        return INSTANCE == null ? INSTANCE = new Progress() : INSTANCE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbVersao1 = new javax.swing.JLabel();
        lbVersao = new javax.swing.JLabel();
        lbVersaoNova = new javax.swing.JLabel();
        lbVersao2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbStatus = new javax.swing.JLabel();
        jpProgress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualização Queijos");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(29, 38, 45));

        jPanel1.setBackground(new java.awt.Color(29, 38, 45));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Versões ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        lbVersao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVersao1.setForeground(new java.awt.Color(255, 255, 255));
        lbVersao1.setText("Atual");

        lbVersao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVersao.setForeground(new java.awt.Color(255, 255, 255));
        lbVersao.setText("1.0.0");

        lbVersaoNova.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVersaoNova.setForeground(new java.awt.Color(255, 255, 255));

        lbVersao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVersao2.setForeground(new java.awt.Color(255, 255, 255));
        lbVersao2.setText("Nova");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbVersao1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbVersao2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbVersaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVersaoNova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbVersao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbVersao)
                        .addComponent(lbVersao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(29, 38, 45));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Processamento ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jPanel2.setDoubleBuffered(false);
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        lbStatus.setBackground(new java.awt.Color(255, 255, 255));
        lbStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText("lbStatus");

        jpProgress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jpProgress.setToolTipText("");
        jpProgress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jpProgress.setPreferredSize(new java.awt.Dimension(150, 50));
        jpProgress.setStringPainted(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(jpProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jpProgress;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JLabel lbVersao;
    private javax.swing.JLabel lbVersao1;
    private javax.swing.JLabel lbVersao2;
    private javax.swing.JLabel lbVersaoNova;
    // End of variables declaration//GEN-END:variables

    public static void updateProgress(int val, boolean sp, String st, String verA, String verN, int sleep, boolean indt) {
        getInstance().getJpProgress().setValue(val);
        getInstance().getJpProgress().setStringPainted(sp);
        getInstance().repaint();
        getInstance().lbStatus.setText(st);

        if (verA != null) {
            getInstance().lbVersaoNova.setText(verA);
        }

        if (verN != null) {
            getInstance().lbVersaoNova.setText(verN);
        }

        if (indt) {
            getInstance().getJpProgress().setIndeterminate(indt);
        }

        getInstance().repaint();
        util.sleep(sleep);
    }

    public static void downloadApplication(String v, UnzipFiles unzip) {
        downloader.download(prop.readPropertie(EPropertie.URL_BASE_GIT), v,
                prop.readPropertie(EPropertie.ARQUIVO_ZIP));
        unzip.unzip(prop.readPropertie(EPropertie.ARQUIVO_ZIP),
                prop.readPropertie(EPropertie.LOCAL_ORIGEM));
    }

    public static void extractFiles(UnzipFiles unzip) {
        util.sleep(5000);
        unzip.createDir(prop.readPropertie(EPropertie.LOCAL_DESTINO));
        unzip.copiar(prop.readPropertie(EPropertie.LOCAL_ORIGEM) + "/bancoqueijos.db",
                prop.readPropertie(EPropertie.LOCAL_DESTINO) + "/bancoqueijos.db");
    }

    public static void updateDatabase(int versao) {
        flywayDb.updateDataBase(prop.readPropertie(EPropertie.DATABASE_URL),
                prop.readPropertie(EPropertie.DATABASE_USER),
                prop.readPropertie(EPropertie.DATABASE_PASSWORD),
                prop.readPropertie(EPropertie.DATABASE_SCRIPT_LOCATION),
                versao == 0);
        util.sleep(2000);
    }

    public static void processar(List<String> versoes, String versaoAtual, TrayIcon trayicon) {

        Progress progress = getInstance();

        UnzipFiles unzip = new UnzipFiles();

        int vAtual = Integer.parseInt(versaoAtual.replace(".", ""));
        boolean sucesso = false;

        for (String v : versoes) {

            int vRem = Integer.parseInt(v.replace(".", ""));

            if (vRem > vAtual) {
                updateProgress(0, true, "Iniciando Download da nova versão...", v, null, 4000, false);

                downloadApplication(v, unzip);
                versaoAtual = v;

                updateProgress(0, false, "Extraindo arquivos...", null, null, 0, true);

                if (vRem == 100) {
                    extractFiles(unzip);
                }

                updateProgress(0, false, "Atualizando banco de dados...", versaoAtual, "", 500, false);

                updateDatabase(vAtual);

                updateProgress(0, false, "Instalando nova versão...", versaoAtual, "", 2000, false);
                unzip.copiar(prop.readPropertie(EPropertie.LOCAL_ORIGEM) + "/" + prop.readPropertie(EPropertie.APLICATION_NAME),
                        prop.readPropertie(EPropertie.LOCAL_DESTINO) + "/" + prop.readPropertie(EPropertie.APLICATION_NAME));

                prop.setProperty(EPropertie.APLICATION_VERSION, versaoAtual);

                updateProgress(0, false, "Removendo arquivos temporários...", versaoAtual, "", 2000, false);

                unzip.deleteDownloadedContent(prop.readPropertie(EPropertie.ARQUIVO_ZIP),
                        prop.readPropertie(EPropertie.LOCAL_ORIGEM));

                updateProgress(0, false, "Versão " + versaoAtual + " atualizada com sucesso!", versaoAtual, "", 2000, false);
            }
            sucesso = true;
        }

        if (sucesso) {
            updateProgress(0, false, "Processo de atualização finalizado!", versaoAtual, "", 2000, false);

            progress.dispose();
            abrirAplicacao(trayicon);
        }

    }

    public JProgressBar getJpProgress() {
        return jpProgress;
    }

    public JLabel getLbStatus() {
        return lbStatus;
    }

    public JLabel getLbVersao() {
        return lbVersao;
    }

    public JLabel getLbVersaoNova() {
        return lbVersaoNova;
    }

    public void setJpProgress(JProgressBar jpProgress) {
        this.jpProgress = jpProgress;
    }

    public void setLbStatus(JLabel lbStatus) {
        this.lbStatus = lbStatus;
    }

    public void setLbVersao(JLabel lbVersao) {
        this.lbVersao = lbVersao;
    }

    public void setLbVersaoNova(JLabel lbVersaoNova) {
        this.lbVersaoNova = lbVersaoNova;
    }

    public static void execCommand(String command) {

        Runtime runTime = Runtime.getRuntime();
        try {
            Process process = runTime.exec(command);
        } catch (IOException ex) {
            Logger.getLogger(Progress.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void abrirAplicacao(TrayIcon trayIcon) {
        trayIcon.displayMessage("Atualizador Queijos", "Clique aqui para abrir o sistema", TrayIcon.MessageType.INFO);
        trayIcon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Runtime runTime = Runtime.getRuntime();
                try {
                    Process process = runTime.exec("java -jar "
                            + prop.readPropertie(EPropertie.LOCAL_DESTINO).replace("\\", "/")
                            + "/" + prop.readPropertie(EPropertie.APLICATION_NAME));
                } catch (IOException ex) {
                    Logger.getLogger(Progress.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public static void setVersaoAtual(String versaoAtual) {
        Progress.versaoAtual = versaoAtual;
    }

    public static void setVersoes(List<String> versoes) {
        Progress.versoes = versoes;
    }

    public void iniciarAtualizacao(List<String> versoes, String versaoAtual, TrayIcon trayicon) {

        Progress janela = Progress.getInstance();

        janela.getJpProgress().setIndeterminate(true);
        janela.getJpProgress().setUI(new MyProgressUI());
        janela.getLbVersao().setText(versaoAtual);

        janela.getJpProgress().setVisible(true);
        janela.getJpProgress().setStringPainted(true);

        janela.repaint();

        janela.processar(versoes, versaoAtual, trayicon);
        TrayIconController.processandoVersao = false;
    }
    
    static class MyProgressUI extends BasicProgressBarUI {

        Rectangle r;

        @Override
        protected void paintIndeterminate(Graphics g, JComponent c) {
            Graphics2D g2d = (Graphics2D) g;
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

            if (r == null) {
                r = new Rectangle();
            }

            r = getBox(r);
            g.setColor(progressBar.getForeground());
            g.fillRect(r.x, r.y, r.width, r.height);
        }
    }

}
